# Generated by Django 3.1.2 on 2020-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('birthplace', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nik', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('datecertification', models.DateField(blank=True, null=True)),
                ('countpatientnumber', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
